## Importing the pakages

In [1]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

## Importing the data

In [10]:
# loadtxt() will generate error
# raw_data_np = np.loadtxt("loan-data.csv", delimiter=";")

raw_data_np = np.genfromtxt("loan-data.csv", delimiter=";", skip_header=1, autostrip=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for incomplete data

In [11]:
np.isnan(raw_data_np).sum()

88005

In [15]:
# nanmax() returns maximum value of an array ignoring NaN values

temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis=0)

C:\Users\MMOHSI~1\AppData\Local\Temp/ipykernel_4452/1702053823.py:4: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis=0)


In [16]:
# any column with NaN mean contains no number

temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [20]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
                           temporary_mean,
                           np.nanmax(raw_data_np, axis=0)])

temporary_stats

C:\Users\MMOHSI~1\AppData\Local\Temp/ipykernel_4452/3508919930.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
C:\Users\MMOHSI~1\AppData\Local\Temp/ipykernel_4452/3508919930.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the dataset

### Splitting the columns

In [37]:
# argwhere() function is used to find the indices of array elements that are non-zero

# squeeze() function is used when we want to remove single-dimensional entries from the shape of an array

columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [43]:
columns_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [42]:
a = np.nan
np.isnan(a==False)

False