# Numpy in Linear Algebra

#### Vectors
- point in space (elements are dimensions of vector)
- 1st order tensor
- scalar addition and multiplication operation strech out or strech in a vector and produce a new vector


In [5]:
import numpy as np

# vectors

vector_1 = np.array([1,2,3,4,5,6,7])
vector_1

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
vector_1 * 2

array([ 2,  4,  6,  8, 10, 12, 14])

In [7]:
vector_1 + 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [8]:
vector_2 = np.array([2,5,6,7,8,9,1])

In [9]:
vector_1 + vector_2

array([ 3,  7,  9, 11, 13, 15,  8])

#### Matrix
- 2nd order tensor
- two dimensional array of numbers

In [10]:
# matrix

matrix_1 = np.random.randint(50, size=(7,7))
matrix_1

array([[10, 48,  0,  6, 42, 21, 45],
       [49,  2, 18, 19,  1, 48, 45],
       [12, 18, 16,  4, 25, 15, 24],
       [37, 30, 48, 37, 47,  6,  2],
       [34, 41, 42, 31,  2, 23, 40],
       [12, 24, 42, 29, 21,  0, 21],
       [16, 44, 21, 27, 34, 40, 18]])

In [11]:
matrix_1 + 5

array([[15, 53,  5, 11, 47, 26, 50],
       [54,  7, 23, 24,  6, 53, 50],
       [17, 23, 21,  9, 30, 20, 29],
       [42, 35, 53, 42, 52, 11,  7],
       [39, 46, 47, 36,  7, 28, 45],
       [17, 29, 47, 34, 26,  5, 26],
       [21, 49, 26, 32, 39, 45, 23]])

In [12]:
matrix_1 * 2

array([[20, 96,  0, 12, 84, 42, 90],
       [98,  4, 36, 38,  2, 96, 90],
       [24, 36, 32,  8, 50, 30, 48],
       [74, 60, 96, 74, 94, 12,  4],
       [68, 82, 84, 62,  4, 46, 80],
       [24, 48, 84, 58, 42,  0, 42],
       [32, 88, 42, 54, 68, 80, 36]])

#### Tensors
- array of numbers with dimension greater than 2
- 3rd and higher ordered tensors
- color images, video data

In [13]:
tensor_1 = np.random.randint(50, size=(3,3,5))
tensor_1

array([[[20, 35, 33, 36, 45],
        [17, 11,  4, 35, 42],
        [45, 13, 42, 14,  3]],

       [[38, 11, 35, 19, 13],
        [46, 23, 34,  9, 17],
        [13, 15, 15, 48, 25]],

       [[42,  8, 24, 46, 38],
        [45, 11, 17,  9, 12],
        [26, 33, 42, 23, 38]]])

In [14]:
tensor_1.shape

(3, 3, 5)

In [15]:
tensor_1.size

45

In [16]:
# dot product

vector_1.dot(vector_2)

159

In [17]:
matrix_A = np.random.randint(10, size=(2,2))
matrix_A

array([[1, 5],
       [1, 5]])

In [18]:
matrix_B = np.matrix(np.random.randint(10,size=(2,2)))
matrix_B

matrix([[3, 4],
        [9, 2]])

In [19]:
matrix_B[0,0]

3

In [20]:
matrix_B[:,0]

matrix([[3],
        [9]])

In [21]:
matrix_C = matrix_B.dot(matrix_A)
matrix_C

matrix([[ 7, 35],
        [11, 55]])

In [22]:
matrix_D = np.random.randint(50,size=(4,4))
matrix_D

array([[ 6, 33, 29, 18],
       [ 0, 47, 27, 43],
       [40, 23, 27, 42],
       [14,  6,  7, 25]])

In [23]:
np.dot(matrix_D,np.identity(4))

array([[ 6., 33., 29., 18.],
       [ 0., 47., 27., 43.],
       [40., 23., 27., 42.],
       [14.,  6.,  7., 25.]])

In [24]:
matrix_E = np.linalg.inv(matrix_D)
matrix_E

array([[-0.06268597,  0.02185747,  0.07709765, -0.121985  ],
       [-0.10515995,  0.07833861,  0.0884309 , -0.20759115],
       [ 0.15693776, -0.09004895, -0.09272286,  0.19766342],
       [ 0.01639996, -0.00582775, -0.0384357 ,  0.10278772]])

In [25]:
print(np.dot(matrix_D,matrix_E))

[[ 1.00000000e+00 -1.35308431e-16 -1.94289029e-16 -9.71445147e-16]
 [-1.38777878e-17  1.00000000e+00 -2.91433544e-16  3.19189120e-16]
 [-6.38378239e-16  4.05925293e-16  1.00000000e+00  2.49800181e-16]
 [-1.52655666e-16  1.40512602e-16 -9.71445147e-17  1.00000000e+00]]


In [26]:
vector_3 = np.random.randint(1,15,4)
vector_3

array([ 3, 14,  7,  1])

##### vdot function

In [27]:
np.vdot(vector_3,matrix_A)

85

#### np.dot and np.matmul
The numpy.dot() function is used for performing matrix multiplication in Python. It also checks the condition for matrix multiplication, that is, the number of columns of the first matrix must be equal to the number of the rows of the second. It works with multi-dimensional arrays also. We can also specify an alternate array as a parameter to store the result. The @ operator for multiplication invokes the matmul() function of an array that is used to perform the same multiplication. 
<br>
The matmul() function broadcasts the array like a stack of matrices as elements residing in the last two indexes, respectively. The numpy.dot() function, on the other hand, performs multiplication as the sum of products over the last axis of the first array and the second-to-last of the second.
<br>
Another difference between the matmul() and the numpy.dot function is that the matmul() function cannot perform multiplication of array with scalar values.

In [30]:
np.dot(matrix_A,matrix_B)

matrix([[48, 14],
        [48, 14]])

In [31]:
np.matmul(matrix_A,matrix_B)

matrix([[48, 14],
        [48, 14]])

#### det

In [33]:
np.linalg.det(matrix_B)

-30.000000000000014